# Generated by Django 2.2.4 on 2019-09-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twittertweet',
            old_name='created_by',
            new_name='user',
        ),
    ]
